#spring:
#    datasource:
#      url: jdbc:oracle:thin:@168.61.2.2:1521:servdb
#      username: center_admin
#      password: timegao
#      driver-class-name: oracle.jdbc.OracleDriver
#    thymeleaf:
#       cache: false
#       mode: LEGACYHTML5
#mybatis:
#  type-aliases-package: com.pjb.entity
#  mapper-locations: classpath*:com.pjb.mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t_shirodemo?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 310429
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.pjb.entity
  mapper-locations: classpath*:com.pjb.mapper/*.xml